In [2]:
import pandas as pd

recommended = pd.read_csv(
    "../data/raw/works_recommended.csv"
)

sanctioned = pd.read_csv(
    "../data/raw/works_sanctioned.csv"
)

completed = pd.read_csv(
    "../data/raw/works_completed.csv"
)

expenditure = pd.read_csv(
    "../data/raw/expenditure.csv"
)

allocated = pd.read_csv(
    "../data/raw/allocated_limit.csv"
)

master = pd.read_csv(
    "../data/processed/master_dataset.csv"
)

C:\Users\thean\AppData\Local\Temp\ipykernel_6336\2392566512.py:3: DtypeWarning: Columns (0,9) have mixed types. Specify dtype option on import or set low_memory=False.
  recommended = pd.read_csv(
C:\Users\thean\AppData\Local\Temp\ipykernel_6336\2392566512.py:7: DtypeWarning: Columns (0,10) have mixed types. Specify dtype option on import or set low_memory=False.
  sanctioned = pd.read_csv(
C:\Users\thean\AppData\Local\Temp\ipykernel_6336\2392566512.py:23: DtypeWarning: Columns (0,9,11,20,22,31) have mixed types. Specify dtype option on import or set low_memory=False.
  master = pd.read_csv(

In [4]:
print(recommended.columns.to_list())
print(recommended.shape)
print(recommended.head(2))
print(sanctioned.columns.to_list())
print(sanctioned.shape)
print(sanctioned.head(2))
print(completed.columns.to_list())
print(completed.shape)
print(completed.head(2))
print(expenditure.columns.to_list())
print(expenditure.shape)
print(expenditure.head(2))
print(master.columns.to_list())
print(master.shape)
print(master.head(2))

['Sr. No.', 'Work category', 'WORK', 'State', 'IDA', "Hon'ble Members of Parliament", 'Constituency', 'Work description', 'Recommended date', 'RECOMMENDED AMOUNT   ( ₹ )', 'Sanction Date']
(73001, 11)
  Sr. No.      Work category  \
0       1      Normal/Others
1       2  Trust and Society

                                                WORK      State  \
0  WS/\t MP620/2024-2025/133166-Construction of b...  Karnataka
1  WS/\t MP620/2025-2026/133167-Construction of r...  Karnataka

                                        IDA Hon'ble Members of Parliament  \
0  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)       Pralhad Venkatesh Joshi
1  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)       Pralhad Venkatesh Joshi

  Constituency                                   Work description  \
0      DHARWAD  Construction of Community Bhavan at Navalgund ...
1      DHARWAD  Construction of College room of  CBS Charitabl...

  Recommended date RECOMMENDED AMOUNT   ( ₹ ) Sanction Date
0      08-Jul-2024                   497185.0   09-Jul-2024
1      08-Jul-2024                   500000.0   18-Sep-2025
['Sr. No.', 'Work category', 'Work', 'State', 'IDA', "Hon'ble Members of Parliament", 'Constituency', 'Work description', 'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )', 'Work Status']
(78000, 12)
  Sr. No.      Work category  \
0       1      Normal/Others
1       2  Trust and Society

                                                Work      State  \
0  WS/\t MP620/2024-2025/133166-Construction of b...  Karnataka
1  WS/\t MP620/2025-2026/133167-Construction of r...  Karnataka

                                        IDA Hon'ble Members of Parliament  \
0  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)       Pralhad Venkatesh Joshi
1  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)       Pralhad Venkatesh Joshi

  Constituency                                   Work description  \
0      DHARWAD  Construction of Community Bhavan at Navalgund ...
1      DHARWAD  Construction of College room of  CBS Charitabl...

  Recommended date Sanction Date Sanction Amount ( ₹ )          Work Status
0      08-Jul-2024   09-Jul-2024              497185.0  Physical Inspection
1      08-Jul-2024   18-Sep-2025              500000.0             Sanction
['Sr. No.', 'Work Category', 'Work', 'State', 'IDA', 'Work Description', "Hon'ble Members of Parliament", 'Constituency', 'Image', 'Completion Date', 'Amount Disbursed ( ₹ )']
(33857, 11)
  Sr. No.  Work Category                                               Work  \
0       7  Normal/Others  WS/MP345/2024-2025/134143-Construction of buil...
1      16  Normal/Others  WS/MP345/2024-2025/134123-Construction of room...

    State                                    IDA  \
0  Kerala  KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)
1  Kerala  KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)

                                    Work Description  \
0  Construction of Building for Brothers Library ...
1  Construction of building for Kadamancode Triba...

  Hon'ble Members of Parliament Constituency   Image Completion Date  \
0         Shri NK Premachandran       KOLLAM  Images     28-Oct-2024
1         Shri NK Premachandran       KOLLAM  Images     06-Dec-2024

  Amount Disbursed ( ₹ )
0                1182588
1                4740188
['Sr. No.', 'State', 'Work', 'Work ID', 'IDA', "Hon'ble Members of Parliament", 'Constituency', 'Expenditure Date', 'Vendor Name', 'Payment Status', 'Fund Disbursed Amount ( ₹ )']
(11001, 11)
  Sr. No.      State                                               Work  \
0       1  Karnataka      Construction of footpaths and pedestrian ways
1       2  Karnataka  Construction of roads, link roads, pathways or...

                       Work ID  \
0  WS/MP18080/2025-2026/181962
1  WS/MP18080/2025-2026/181963

                                                 IDA  \
0  Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAG...
1  Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAG...

  Hon'ble Members of Parliament        Constituency Expenditure Date  \
0                    SUNIL BOSE  CHAMARAJANAGAR(SC)      20-Aug-2026
1                    SUNIL BOSE  CHAMARAJANAGAR(SC)      20-Aug-2026

                   Vendor Name       Payment Status  \
0  KRIDL BHUSIRI ACCOUNT WORKS  Payment In-Progress
1  KRIDL BHUSIRI ACCOUNT WORKS  Payment In-Progress

  Fund Disbursed Amount ( ₹ )
0                      250000
1                      250000
['sr._no._x', 'work_category_x', 'work', 'state_x', 'ida_x', "hon'ble_members_of_parliament_x", 'constituency_x', 'work_description_x', 'recommended_date_x', 'recommended_amount___(_₹_)', 'sanction_date_x', 'sr._no._y', 'work_category_y', 'state_y', 'ida_y', "hon'ble_members_of_parliament_y", 'constituency_y', 'work_description_y', 'recommended_date_y', 'sanction_date_y', 'sanction_amount_(_₹_)', 'work_status', 'sr._no.', 'work_category', 'state', 'ida', 'work_description', "hon'ble_members_of_parliament", 'constituency', 'image', 'completion_date', 'amount_disbursed_(_₹_)']
(73001, 32)
  sr._no._x    work_category_x  \
0         1      Normal/Others
1         2  Trust and Society

                                                work    state_x  \
0  WS/\t MP620/2024-2025/133166-Construction of b...  Karnataka
1  WS/\t MP620/2025-2026/133167-Construction of r...  Karnataka

                                      ida_x hon'ble_members_of_parliament_x  \
0  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)         Pralhad Venkatesh Joshi
1  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)         Pralhad Venkatesh Joshi

  constituency_x                                 work_description_x  \
0        DHARWAD  Construction of Community Bhavan at Navalgund ...
1        DHARWAD  Construction of College room of  CBS Charitabl...

  recommended_date_x recommended_amount___(_₹_)  ... sr._no.  work_category  \
0        08-Jul-2024                   497185.0  ...    20.0  Normal/Others
1        08-Jul-2024                   500000.0  ...     NaN            NaN

       state                                       ida  \
0  Karnataka  DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)
1        NaN                                       NaN

                                    work_description  \
0  Construction of Community Bhavan at Navalgund ...
1                                                NaN

  hon'ble_members_of_parliament constituency   image completion_date  \
0       Pralhad Venkatesh Joshi      DHARWAD  Images     14-Oct-2024
1                           NaN          NaN     NaN             NaN

  amount_disbursed_(_₹_)
0               497185.0
1                    NaN

[2 rows x 32 columns]

In [3]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73001 entries, 0 to 73000
Data columns (total 32 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   sr._no._x                        73001 non-null  object
 1   work_category_x                  73001 non-null  object
 2   work                             73001 non-null  object
 3   state_x                          73001 non-null  object
 4   ida_x                            73001 non-null  object
 5   hon'ble_members_of_parliament_x  73001 non-null  object
 6   constituency_x                   73001 non-null  object
 7   work_description_x               72902 non-null  object
 8   recommended_date_x               73001 non-null  object
 9   recommended_amount___(_₹_)       73001 non-null  object
 10  sanction_date_x                  66057 non-null  object
 11  sr._no._y                        66057 non-null  object
 12  work_category_y                  66057 non-null  object
 13  state_y                          66057 non-null  object
 14  ida_y                            66057 non-null  object
 15  hon'ble_members_of_parliament_y  66057 non-null  object
 16  constituency_y                   66057 non-null  object
 17  work_description_y               65965 non-null  object
 18  recommended_date_y               66057 non-null  object
 19  sanction_date_y                  66057 non-null  object
 20  sanction_amount_(_₹_)            66057 non-null  object
 21  work_status                      66057 non-null  object
 22  sr._no.                          33206 non-null  object
 23  work_category                    33206 non-null  object
 24  state                            33206 non-null  object
 25  ida                              33206 non-null  object
 26  work_description                 33128 non-null  object
 27  hon'ble_members_of_parliament    33206 non-null  object
 28  constituency                     33206 non-null  object
 29  image                            24078 non-null  object
 30  completion_date                  33206 non-null  object
 31  amount_disbursed_(_₹_)           33134 non-null  object
dtypes: object(32)
memory usage: 17.8+ MB

In [9]:
import re

def extract_project_id(text):

    if pd.isna(text):
        return None

    text = str(text).replace("\t", "")
    text = " ".join(text.split())

    match = re.search(
        r"(WS\/\s*MP\d+\/\d{4}-\d{4}\/\d+)",
        text,
        flags=re.IGNORECASE
    )

    if match:
        return (
            match.group(1)
            .replace(" ", "")
        )

    return None

In [10]:
recommended["project_id"] = (
    recommended["WORK"]
    .apply(extract_project_id)
)

sanctioned["project_id"] = (
    sanctioned["Work"]
    .apply(extract_project_id)
)

completed["project_id"] = (
    completed["Work"]
    .apply(extract_project_id)
)

In [11]:
print(
    recommended["project_id"]
    .nunique()
)

print(
    sanctioned["project_id"]
    .nunique()
)

print(
    completed["project_id"]
    .nunique()
)

66056
77999
33856

In [12]:
print(
    recommended["project_id"]
    .duplicated()
    .sum()
)

print(
    sanctioned["project_id"]
    .duplicated()
    .sum()
)

print(
    completed["project_id"]
    .duplicated()
    .sum()
)

print(
    recommended["project_id"]
    .isnull()
    .sum()
)

print(
    sanctioned["project_id"]
    .isnull()
    .sum()
)

print(
    completed["project_id"]
    .isnull()
    .sum()
)

6944
0
0
6945
1
1

In [15]:
recommended[
    recommended["WORK"].isna()
].head(20)

Empty DataFrame
Columns: [Sr. No., Work category, WORK, State, IDA, Hon'ble Members of Parliament, Constituency, Work description, Recommended date, RECOMMENDED AMOUNT   ( ₹ ), Sanction Date, project_id]
Index: []

In [16]:
recommended[
    recommended["WORK"].isna()
].shape

(0, 12)

In [17]:
recommended.isna().all(axis=1).sum()

np.int64(0)

In [21]:
recommended["WORK"].duplicated().sum()

np.int64(6849)

In [22]:
recommended[
    recommended["WORK"].duplicated(keep=False)
][["WORK"]].head(20)

                                                   WORK
231                      NA-Development of public parks
232                      NA-Development of public parks
242   NA-Construction of community centers and commu...
323   NA-Construction of roads, link roads, pathways...
324           NA-Purchase of immovable sports equipment
325                      NA-Development of public parks
349   NA-Construction of roads, link roads, pathways...
352   NA-Construction of roads, link roads, pathways...
440   NA-Construction of roads, link roads, pathways...
508   NA-Construction of additional rooms and halls ...
558   NA-Construction of roads, link roads, pathways...
920                       NA-Setting up of laboratories
1417  NA-Construction of roads, link roads, pathways...
1572             NA-Installing tube-wells and borewells
1583          NA-Construction of bus-sheds or bus-stops
1584  NA-Construction of common work sheds/ common c...
1588  NA-Purchase of ambulances (Four, three and two...
1738                     NA-Construction of water tanks
1739                     NA-Construction of water tanks
1751  NA-Crematoriums/energy efficient crematoriums ...

In [23]:
recommended["is_valid_project"] = (
    recommended["WORK"]
    .astype(str)
    .str.startswith("WS/")
)

In [24]:
recommended["is_valid_project"].value_counts()

is_valid_project
True     66056
False     6945
Name: count, dtype: int64

In [25]:
recommended_clean = (
    recommended[
        recommended["is_valid_project"]
    ]
    .copy()
)

In [30]:
print(recommended_clean.shape)

print(recommended_clean["WORK"].duplicated().sum())

(66056, 13)
0

In [29]:
print(
    recommended_clean["project_id"]
    .nunique()
)

print(
    recommended_clean["project_id"]
    .duplicated()
    .sum()
)

print(
    recommended_clean["project_id"]
    .isnull()
    .sum()
)

66056
0
0